-- MySQL Script generated by MySQL Workbench
-- Wed Mar 27 19:25:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DBMB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBMB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBMB` DEFAULT CHARACTER SET utf8 ;
USE `DBMB` ;

-- -----------------------------------------------------
-- Table `DBMB`.`Generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBMB`.`Generos` ;

CREATE TABLE IF NOT EXISTS `DBMB`.`Generos` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMB`.`Tipos_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBMB`.`Tipos_clientes` ;

CREATE TABLE IF NOT EXISTS `DBMB`.`Tipos_clientes` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMB`.`Estados_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBMB`.`Estados_clientes` ;

CREATE TABLE IF NOT EXISTS `DBMB`.`Estados_clientes` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMB`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBMB`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `DBMB`.`Clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `documento_identidad` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `genero` INT NULL,
  `relacion` INT NULL,
  `tipo` INT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_Clientes_Generos1_idx` (`genero` ASC) ,
  INDEX `familiar_idx` (`relacion` ASC) ,
  INDEX `fk_Clientes_Tipos_clientes1_idx` (`tipo` ASC) ,
  INDEX `fk_Clientes_Estados_clientes1_idx` (`estado` ASC) ,
  CONSTRAINT `fk_Clientes_Generos1`
    FOREIGN KEY (`genero`)
    REFERENCES `DBMB`.`Generos` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `familiar`
    FOREIGN KEY (`relacion`)
    REFERENCES `DBMB`.`Clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_Tipos_clientes1`
    FOREIGN KEY (`tipo`)
    REFERENCES `DBMB`.`Tipos_clientes` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_Estados_clientes1`
    FOREIGN KEY (`estado`)
    REFERENCES `DBMB`.`Estados_clientes` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMB`.`Propuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBMB`.`Propuestas` ;

CREATE TABLE IF NOT EXISTS `DBMB`.`Propuestas` (
  `id_propuesta` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATE NULL,
  `estado` VARCHAR(50) NULL,
  `destino` VARCHAR(200) NULL,
  `nombre` VARCHAR(200) NULL,
  PRIMARY KEY (`id_propuesta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMB`.`Inteacciones_redes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBMB`.`Inteacciones_redes` ;

CREATE TABLE IF NOT EXISTS `DBMB`.`Inteacciones_redes` (
  `id_inteaccion` INT NOT NULL AUTO_INCREMENT,
  `red_social` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_inteaccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMB`.`Publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBMB`.`Publicaciones` ;

CREATE TABLE IF NOT EXISTS `DBMB`.`Publicaciones` (
  `id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `id_propuesta` INT NULL,
  `Inid_inteaccion` INT NULL,
  `tipo` VARCHAR(45) NULL,
  `metrica` INT NULL,
  PRIMARY KEY (`id_publicacion`),
  INDEX `fk_Publicaciones_Propuestas1_idx` (`id_propuesta` ASC) ,
  INDEX `fk_Publicaciones_Inteacciones_redes1_idx` (`Inid_inteaccion` ASC) ,
  CONSTRAINT `fk_Publicaciones_Propuestas1`
    FOREIGN KEY (`id_propuesta`)
    REFERENCES `DBMB`.`Propuestas` (`id_propuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publicaciones_Inteacciones_redes1`
    FOREIGN KEY (`Inid_inteaccion`)
    REFERENCES `DBMB`.`Inteacciones_redes` (`id_inteaccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMB`.`Promocion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBMB`.`Promocion` ;

CREATE TABLE IF NOT EXISTS `DBMB`.`Promocion` (
  `id_promocion` INT NOT NULL AUTO_INCREMENT,
  `id_publicacion` INT NOT NULL,
  `Clientes_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_promocion`),
  INDEX `fk_Preventas_Publicaciones1_idx` (`id_publicacion` ASC) ,
  INDEX `fk_Preventas_Clientes1_idx` (`Clientes_id_cliente` ASC) ,
  CONSTRAINT `fk_Preventas_Publicaciones1`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `DBMB`.`Publicaciones` (`id_publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Preventas_Clientes1`
    FOREIGN KEY (`Clientes_id_cliente`)
    REFERENCES `DBMB`.`Clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




INSERT INTO generos (genero) VALUES ('Femenino'), ('Masculino');

INSERT INTO tipos_clientes (tipo) VALUES ('C.I'), ('RIF');

INSERT INTO
    inteacciones_redes (red_social)
VALUES ('facebook'),
    ('instagram'),
    ('tiktok'),
    ('X');

INSERT INTO
    estados_clientes (estado)
VALUES ('Completo'),
    ('Pendiente');










INSERT INTO
    clientes (
        nombre, apellido, direccion, documento_identidad, contacto, email, fecha_nacimiento, genero, tipo, estado
    )
VALUES (
        'Luis', 'González', 'Calle 123', '123456789', '123-456-7890', 'luis@email.com', '1990-05-15', 2, 1, 2
    ),
    (
        'María', 'Martínez', 'Avenida 456', '987654321', '987-654-3210', 'maria@email.com', '1985-10-20', 1, 1, 1
    ),
    (
        'Carlos', 'Ramírez', 'Carrera 789', '456789123', '456-789-1230', 'carlos@email.com', '1978-03-25', 2, 2, 2
    ),
    (
        'Ana', 'López', 'Pasaje 567', '789123456', '789-123-4560', 'ana@email.com', '1995-12-10', 1, 2, 2
    ),
    (
        'wilita', 'mala paga', 'Antimano', '200901231', '04161239213123', 'wilita_tovar@gmail.com', '1995-03-01', 2, 1, 1
    );




INSERT INTO propuestas (fecha_creacion, estado,destino ,nombre) VALUES ("2024-03-27","revicion","La Guaira", "Paquete Playero");
INSERT INTO propuestas (fecha_creacion,destino ,nombre) VALUES ("2024-03-27","Caracas", "Viaje a la capital");



